// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CameraController from "./camera_controller"
application.register("camera", CameraController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import FilmController from "./film_controller"
application.register("film", FilmController)

import FrameController from "./frame_controller"
application.register("frame", FrameController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)

import RollController from "./roll_controller"
application.register("roll", RollController)
