// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CameraController from "./camera_controller"
application.register("camera", CameraController)

import CameraModalController from "./camera_modal_controller"
application.register("camera-modal", CameraModalController)

import FilmController from "./film_controller"
application.register("film", FilmController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)
